#!/usr/bin/env python

import sys
import os
import subprocess


def get_path_component(a_path):
  res = []
  while a_path != '':
    a_path, tail = os.path.split(a_path)
    res.insert(0, tail)
  return res


def gen_env():
  env = {}
  env.update(os.environ)
  if 'TZ' not in env:
    env['TZ'] = 'UTC'
  python_path = [
      os.path.normpath(
          os.getcwd())
  ]
  python_path = ':'.join(python_path)
  if 'PYTHONPATH' in env:
    env['PYTHONPATH'] += ':' + python_path
  else:
    env['PYTHONPATH'] = python_path
  return env


def main(argv):
  if len(argv) < 2:
    sys.stderr.write("No python file is given.\n")
    return 1

  py_path = argv[1]
  assert os.path.isfile(py_path)
  assert not os.path.isabs(py_path)

  a_path, ext = os.path.splitext(py_path)
  comp = get_path_component(a_path)
  assert ext == '.py'
  assert len(comp) >= 1, len(comp)
  module_path = '.'.join(comp)

  args = ['python3', '-B', '-m', module_path] + argv[2:]
  os.execvpe('python3', args, gen_env())


if __name__ == '__main__':
  sys.exit(main(sys.argv))
